"""
server/models/conversation.py

Pydantic models for PS-8 Conversational Follow-up Q&A (Phase 11).
Strictly enforces:
- Conversation history is non-authoritative context only; VEO is the sole financial authority.
- Tri-state epistemic preservation across multi-turn interactions.
- Bounded history budget (max turns).
- Context isolation per transaction.
"""

from enum import Enum
from datetime import datetime, timezone
from typing import List, Optional
from uuid import uuid4
from pydantic import BaseModel, Field, ConfigDict

from server.validation.models import ResponseValidationResult


class MessageRole(str, Enum):
    """Origin of a conversation message."""
    USER = "user"
    ASSISTANT = "assistant"


class ChatMessage(BaseModel):
    """An individual conversational message turn."""
    message_id: str = Field(default_factory=lambda: str(uuid4()), description="Unique message ID")
    role: MessageRole = Field(..., description="Message author role (user or assistant)")
    content: str = Field(..., description="Message textual content")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Message creation timestamp (UTC)"
    )
    validated: bool = Field(default=True, description="True if response has been verified by Phase 9 validator")
    llm_used: bool = Field(default=False, description="True if generated by LLM, False if deterministic fallback")
    is_fallback: bool = Field(default=False, description="True if substituted with deterministic fallback")
    validation_result: Optional[ResponseValidationResult] = Field(
        default=None,
        description="Detailed audit report from Phase 9 ResponseValidator"
    )

    model_config = ConfigDict(frozen=True)


class ConversationContext(BaseModel):
    """
    Session container holding conversational messages for an active investigation.
    Strictly anchored to a single canonical transaction_id and investigation_id.
    """
    conversation_id: str = Field(default_factory=lambda: f"conv_{uuid4().hex[:12]}", description="Unique conversation session ID")
    transaction_id: str = Field(..., description="Canonical anchor transaction ID this conversation is grounded in")
    investigation_id: str = Field(..., description="VEO investigation ID (veo_pay_...)")
    messages: List[ChatMessage] = Field(default_factory=list, description="Ordered chronological message turns")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Conversation session creation timestamp"
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp of most recent message turn"
    )

    model_config = ConfigDict(frozen=True)
