"""
server/agent/models.py

Pydantic models and data contracts for the AI Settlement Analyst (Phase 8 & 11).
Enforces:
- Separation of untrusted user question from authoritative VEO
- Structured dual-channel response container (internal + merchant)
- Detailed observability metadata (provider, model, latency, tokens)
- Epistemic fact tracking (KNOWN, INFERRED, UNKNOWN)
- Multi-turn conversation context and message linking
"""

from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field, ConfigDict

from server.evidence.models import VerifiedEvidencePack
from server.validation.models import ResponseValidationResult
from server.models.conversation import ChatMessage


class ProviderMetadata(BaseModel):
    """Execution telemetry and identity metadata for LLM provider invocation."""
    provider: str = Field(..., description="Provider name (e.g. gemini, groq, mock)")
    model: str = Field(..., description="Specific model used (e.g. gemini-1.5-flash, llama-3.3-70b-versatile)")
    latency_ms: Optional[float] = Field(default=None, description="Inference latency in milliseconds")
    prompt_tokens: Optional[int] = Field(default=None, description="Input prompt tokens if reported by provider")
    completion_tokens: Optional[int] = Field(default=None, description="Output completion tokens if reported")

    model_config = ConfigDict(frozen=True)


class AIAnalystRequest(BaseModel):
    """
    Input contract for the AI Settlement Analyst.
    Combines the authoritative, verified VEO with an optional user question and prior chat history.
    """
    evidence_pack: VerifiedEvidencePack = Field(
        ...,
        description="The canonical, authoritative Verified Evidence Pack (VEO)"
    )
    question: Optional[str] = Field(
        default=None,
        description="Optional natural-language inquiry from support engineer or merchant (untrusted user input)"
    )
    query_identifier: Optional[str] = Field(
        default=None,
        description="Original query string supplied by user"
    )
    conversation_id: Optional[str] = Field(
        default=None,
        description="Optional session ID for multi-turn conversational follow-up"
    )
    history: Optional[List[ChatMessage]] = Field(
        default=None,
        description="Bounded list of prior conversation turns for reference resolution (non-authoritative)"
    )

    model_config = ConfigDict(frozen=True)


class AIAnalystResponse(BaseModel):
    """
    Structured output contract from the AI Settlement Analyst.
    Prepares structured claims and dual-channel explanations suitable for Phase 9 validation.
    """
    internal_summary: str = Field(
        ...,
        description="Technical, highly factual breakdown for payment operations and support engineers"
    )
    merchant_friendly_response: str = Field(
        ...,
        description="Courteous, safe, non-technical explanation suitable for merchants"
    )
    merchant_explanation: str = Field(
        ...,
        description="Alias for merchant_friendly_response"
    )
    answer: Optional[str] = Field(
        default=None,
        description="Direct grounded answer to specific user question if asked"
    )
    known_facts: List[str] = Field(
        default_factory=list,
        description="Verified factual statements directly established by source records"
    )
    inferred_facts: List[str] = Field(
        default_factory=list,
        description="Logical inferences derived deterministically from multi-system evidence"
    )
    unknown_facts: List[str] = Field(
        default_factory=list,
        description="Facts explicitly unrecorded or absent from evidence (retained as unknown)"
    )
    llm_used: bool = Field(
        default=False,
        description="True if generated by an LLM, False if generated by deterministic template fallback"
    )
    provider: Optional[str] = Field(
        default=None,
        description="Provider that generated this response (e.g. gemini, groq, mock, deterministic_fallback)"
    )
    model: Optional[str] = Field(
        default=None,
        description="Model identifier"
    )
    prompt_version: str = Field(
        default="1.0.0",
        description="Semantic version of prompt template used"
    )
    validated: bool = Field(
        default=True,
        description="True if explanation adheres strictly to VEO facts"
    )
    validation_result: Optional[ResponseValidationResult] = Field(
        default=None,
        description="Detailed audit result from Phase 9 response validator"
    )
    conversation_id: Optional[str] = Field(
        default=None,
        description="Active conversation session ID if part of a multi-turn thread"
    )
    message_id: Optional[str] = Field(
        default=None,
        description="Assigned unique message ID for this response turn"
    )

    model_config = ConfigDict(frozen=True)
